---
- hosts: dynamic_hosts
  remote_user: ubuntu
  tasks:
    - set_fact: vars_file="default"
      when: vars_file is undefined
    - name: include variables
      include_vars: vars/{{vars_file}}.yml
    - name: print hello
      shell: echo {{ message }}
